export interface IStringString {
  [key: string]: string ;
}

export const sameCharEn = [
  'A',
  'a',
  'B',
  'C',
  'c',
  'E',
  'e',
  'H',
  'K',
  'k',
  'M',
  'O',
  'o',
  'P',
  'p',
  'T',
  'X',
  'x',
  'y',
];
export const sameCharRu = [
  'А',
  'а',
  'В',
  'С',
  'с',
  'Е',
  'е',
  'Н',
  'К',
  'к',
  'М',
  'О',
  'о',
  'Р',
  'р',
  'Т',
  'Х',
  'х',
  'у',
];

export function sameChar(str: string) {
  sameCharEn.forEach((item, index) => {
    let re = new RegExp(item, 'g');
    str = str.replace(re, sameCharRu[index]);
  });
  return str;
}

export const colOrderObj = {
  opt1: [
    'numTiShem60',
    'kodTi60',
    'naimTi60',
    'tipSch60',
    'kanaly60',
    // "tiAiis",
    'gr',
    'numTiSop',
    'naimTiSop',
    'numSchSop',
    'tipSchSop',
    'kttSop',
    'ktnSop',
    'kodTi80',
    'naimTi80',
    'tipSch80',
    'kanaly80',
    'naimTi82',
    'numSchSch',
    'tipSchSch',
    'tipSchDB',
    'numSchDB',
    'kttDB',
    'ktnDB',
  ],
  opt2: [
    'numTiShem60',
    'naimTi60',
    'naimTiSop',
    'naimTi80',
    'naimTi82',
    'tipSch60',
    'tipSchSop',
    'tipSch80',
    'tipSchSch',
    'tipSchDB',
    // "tiAiis",
    'gr',
    'numTiSop',
    'numSchSop',
    'numSchSch',
    'numSchDB',
    'kttSop',
    'kttDB',
    'ktnSop',
    'ktnDB',
    'kodTi60',
    'kodTi80',
    'kanaly80',
    'kanaly60',
  ],
  opt3: [
    'numTiShem60Pre',
    'kodTi60Pre',
    'naimTi60Pre',
    'tipSch60Pre',
    'kanaly60Pre',
    'numTiShem60',
    'kodTi60',
    'naimTi60',
    'tipSch60',
    'kanaly60',
    // "tiAiis",
    'gr',
    'numTiSop',
    'naimTiSop',
    'numSchSop',
    'tipSchSop',
    'kttSop',
    'ktnSop',
    'kodTi80',
    'naimTi80',
    'tipSch80',
    'kanaly80',
    'naimTi82',
    'numSchSch',
    'tipSchSch',
    'tipSchDB',
    'numSchDB',
    'kttDB',
    'ktnDB',
  ],
};

export const colFullName: IStringString = {
  numTiShem60Pre: '№ТИ Сх60 Пред',
  kodTi60Pre: 'кодТИ60 Пред',
  naimTi60Pre: 'наимТИ60 Пред',
  tipSch60Pre: 'типСч60 Пред',
  kanaly60Pre: 'каналы60 Пред',
  numTiShem60: '№ТИ Сх60',
  kodTi60: 'кодТИ60',
  naimTi60: 'наимТИ60',
  tipSch60: 'типСч60',
  kanaly60: 'каналы60',
  // tiAiis: "ТИ в АИИС",
  gr: '№ ГР',
  numTiSop: '№ТИ СОП',
  naimTiSop: 'наим ТИ СОП',
  naimTi80: 'наим ТИ 80',
  naimTi82: 'наим ТИ 82',
  numSchDB: '№ Сч БД',
  numSchSop: '№ Сч СОП',
  numSchSch: '№ СЧ Сч',
  tipSchSop: 'типСчСОП',
  tipSch80: 'тип Сч 80',
  tipSchSch: 'типСчСч',
  tipSchDB: 'типСчБД',
  kttSop: 'Ктт СОП',
  kttDB: 'Ктт БД',
  ktnSop: 'Ктн СОП',
  ktnDB: 'Ктн БД',
  kodTi80: 'кодТИ80',
  kanaly80: 'каналы80',
};

// export const colGroupOrderObj = {
//   opt1: ["60 xml", "СОП", "80 XML", "82 XML", "Сч", "БД"],
//   opt2: ["60 xml", "СОП", "80 XML", "82 XML", "Сч", "БД"],
// };
